apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- if .Values.initJob.helmHook }}
    "helm.sh/hook": {{ .Values.initJob.helmHook }}
    "helm.sh/hook-delete-policy": {{ .Values.initJob.helmHookDeletePolicy | default "before-hook-creation,hook-succeeded" }}
    {{- end }}
    {{- if or .Values.initJob.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.initJob.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: redis-cluster-init
          image: {{ include "redis-cluster.image" . }}
          {{- if .Values.initJob.resources }}
          resources: {{- toYaml .Values.initJob.resources | nindent 12 }}
          {{- end }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redis-cluster.secretName" . }}
                  key: {{ template "redis-cluster.secretPasswordKey" . }}
          command:
            - "sh"
            - "-c"
            - |
              NODES={{ .Values.cluster.nodes }}
              FULLNAME="{{ include "common.names.fullname" . }}"
              HEADLESS="${FULLNAME}-headless"
              echo "Waiting for all $NODES Redis pods to be ready..."
              i=0
              while [ $i -lt $NODES ]; do
                until redis-cli -h ${FULLNAME}-$i.${HEADLESS} -a $REDIS_PASSWORD ping | grep PONG; do
                  echo "Waiting for ${FULLNAME}-$i..."
                  sleep 2
                done
                i=$((i+1))
              done

              echo "All Redis pods are ready. Creating cluster..."
              NODE_LIST=""
              i=0
              while [ $i -lt $NODES ]; do
                NODE_LIST="$NODE_LIST ${FULLNAME}-$i.${HEADLESS}:6379"
                i=$((i+1))
              done

              echo "Cluster nodes: $NODE_LIST"
              redis-cli --cluster create $NODE_LIST --cluster-replicas 1 -a $REDIS_PASSWORD --cluster-yes

      serviceAccountName: default
