{{- /*
Redis Cluster Update Job (Bitnami official image)
Automatically add new StatefulSet Pods to the cluster
*/ -}}

{{- if and .Values.cluster.update.addNodes (or (and .Values.cluster.externalAccess.enabled .Values.cluster.externalAccess.service.loadBalancerIP) (not .Values.cluster.externalAccess.enabled)) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-cluster-update
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.updateJob.helmHook }}
    "helm.sh/hook": {{ .Values.updateJob.helmHook }}
    "helm.sh/hook-delete-policy": {{ .Values.updateJob.helmHookDeletePolicy | default "before-hook-creation,hook-succeeded" }}
    {{- end }}
    {{- if or .Values.updateJob.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.updateJob.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  activeDeadlineSeconds: {{ .Values.updateJob.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.names.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: {{ .Values.updateJob.automountServiceAccountToken }}
      restartPolicy: OnFailure
      {{- if .Values.updateJob.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.updateJob.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.updateJob.affinity }}
      affinity:
{{ toYaml .Values.updateJob.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.updateJob.tolerations }}
      tolerations:
{{ toYaml .Values.updateJob.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: trigger
          image: {{ include "redis-cluster.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ['/bin/bash', '-c']
          args:
            - |
              echo "Starting Redis cluster update..."

              # If password is configured
              {{- if .Values.usePassword }}
              {{- if .Values.usePasswordFile }}
              export REDISCLI_AUTH=$(cat /opt/redis/secrets/redis-password)
              {{- else }}
              export REDISCLI_AUTH="{{ .Values.password }}"
              {{- end }}
              {{- end }}

              firstNodeIP="{{ template "common.names.fullname" . }}-0.{{ template "common.names.fullname" . }}-headless"
              echo "First node: $firstNodeIP"

              # Internal StatefulSet scaling
              currentMasterNodesNum=$(( {{ .Values.cluster.update.currentNumberOfNodes }} / (( {{ .Values.cluster.update.currentNumberOfReplicas }} + 1 )) ))
              slaveNodesEndPos=$(( {{ .Values.cluster.update.currentNumberOfNodes }} + (($REDIS_CLUSTER_REPLICAS - {{ .Values.cluster.update.currentNumberOfReplicas }})) * $currentMasterNodesNum ))

              for node in $(seq $((1 + {{ .Values.cluster.update.currentNumberOfNodes }})) {{ .Values.cluster.nodes }}); do
                newNodeIndex=$((node - 1))
                newNodeIP="{{ template "common.names.fullname" . }}-${newNodeIndex}.{{ template "common.names.fullname" . }}-headless"

                until [[ $(redis-cli -h "$newNodeIP" -p {{ .Values.redis.containerPorts.redis }} ping) == "PONG" ]]; do
                  echo "Node $newNodeIP not ready..."
                  sleep 5
                done

                slave=()
                if (( $REDIS_CLUSTER_REPLICAS >= 1 )) && (( (( $newNodeIndex < $slaveNodesEndPos )) || (( (( $newNodeIndex >= $slaveNodesEndPos )) && (( $newNodeIndex % (( $REDIS_CLUSTER_REPLICAS + 1 )) )) )) )); then
                  slave+=("--cluster-slave")
                fi

                until redis-cli --cluster add-node "${newNodeIP}:{{ .Values.redis.containerPorts.redis }}" "${firstNodeIP}:{{ .Values.redis.containerPorts.redis }}" ${slave[@]}; do
                  echo "Failed to add node $newNodeIP, retrying..."
                  sleep 5
                done
              done

              # Rebalance the cluster
              until redis-cli --cluster rebalance "${firstNodeIP}:{{ .Values.redis.containerPorts.redis }}" --cluster-use-empty-masters; do
                echo "Rebalance failed, retrying..."
                sleep 5
              done

              echo "Redis cluster update completed!"
          env:
            - name: BITNAMI_DEBUG
              value: {{ ternary "true" "false" .Values.image.debug | quote }}
            {{- if .Values.usePassword }}
            {{- if .Values.usePasswordFile }}
            - name: REDIS_PASSWORD_FILE
              value: "/opt/redis/secrets/redis-password"
            {{- else }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redis-cluster.secretName" . }}
                  key: {{ template "redis-cluster.secretPasswordKey" . }}
            {{- end }}
            {{- end }}
{{- end }}
